version: '4'
services:
  postgres:
    container_name: patrones
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

